---
title: Person's Homepage
headerStyle: clean
background:
  image: https://wallpapercave.com/wp/wp4565843.jpg
  blur: md
  saturate: 50
  brightness: 50
  opacity: 70
theme: dark
color: slate
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: false
layout:
  Quick:
    header: false
    style: column
  Access:
    header: false
    style: column
  Calendar:
    header: false
    style: column
  Infrastructure:
    header: true
    style: row
    columns: 4
  Network and IoT:
    header: true
    style: row
    columns: 4
  Media:
    header: true
    style: row
    columns: 4
  Monitoring:
    header: true
    style: row
    columns: 4
  Tor Stack:
    header: true
    style: row
    columns: 4
  Access and Services:
    header: true
    style: row
    columns: 4
